#default config.yml
#Demigods Configuration File
#Global Settings
update: true
motd: true
active_worlds:
- world
- world_nether
- world_the_end
inactive_worlds: []
globalfavormultiplier: 1.0
globalexpmultiplier: 1.0
globalfavorcap: 140000
save_pretty: false
max_devotion_lost_on_death: 15000
max_target_range: 100
max_hp: 3000
pvp_exp_bonus: 1.5
broadcast_new_aspects: true
stat_display_frequency_in_seconds: 0
confirm_time: 10
pvp_area_delay_time: 10
battle_interval_seconds: 10
start_delay_seconds: 0.1
favor_regen_seconds: 0.5
hp_regen_seconds: 10.0
save_interval_seconds: 300
balance_teams: true
ascension_cap: 100
allow_skills_everywhere: false
use_new_pvp_zones: true
friendly_fire: false
friendly_fire_message: true
noob_level: 25000
no_cost_aspect_mode: false
no_faction_aspect_mode: false
debug_data: false
debug_invisible_walls: false
mongo:
  use: false
  hostname: 127.0.0.1
  port: 27017
  database: demigods
  username: demigods
  password: demigods
pantheon:
  norse: true
  greek: false
#Deity specific
#Ares
#Hades
#Poseidon
poseidon:
    drown_world_height_limit: 89
#Zeus
#Atlas
#Cronus
#Prometheus
#Rhea
