name: DemigodsClassic
main: com.demigodsrpg.demigods.classic.DGClassic
version: ${project.version}
description: Ally yourself with mythical deities and battle in the name of the Gods or Titans.
authors: [marinating, HmmmQuestionMark, _Alex, TheFatDemon, janie177]
softdepend: [WorldGuard, WorldEdit, Multiverse-Core]
commands:
  alliance:
    usage: /alliance message
    aliases: [a]
  binds:
    usage: /binds
    aliases: [b]
  check:
    usage: /check
    aliases: [c]
  demigods:
    usage: /demigods [subject]
    aliases: [d, dg, demigod]
  adddevotion:
    usage: /adddevotion [name, deity, amount]
    permission: demigods.admin.adddevotion
  checkplayer:
    usage: /checkplayer [name]
  givedeity:
    usage: /givedeity [name, deity]
    permission: demigods.admin.givedeity