name: DemigodsRPG
main: com.demigodsrpg.DGBukkitPlugin
version: ${project.version}
description: Ally yourself with mythical deities and battle in the name of the Gods or Titans.
authors: [HmmmQuestionMark, _Alex, marinating, janie177, TheFatDemon]
softdepend: [Chitchat, WorldGuard]
commands:
  ## Everyday Commands
  family:
    usage: /family
    aliases: [f]
  binds:
    usage: /binds
    aliases: [b]
  check:
    usage: /check
    aliases: [c]
  aspect:
    usage: /aspect [subcommand] [args...]
  demigods:
    usage: /demigods [subject]
    aliases: [d, dg, demigod]
  cleanse:
    usage: /cleanse [all|player] [all]
  shrine:
    usage: /shrine
    aliases: [s, sh, shrines]
  values:
    usage: /values
    aliases: [v]
  ## Admin Commands
  adminmode:
    usage: /adminmode
    permissions: demigods.admin
    aliases: [am, dga, dgam]
  selectarea:
    usage: /selectarea
    aliases: [sa, areaselect]
  createfamilyarea:
    usage: /createfamilyarea [family]
    aliases: [makefamilyarea]
  checkplayer:
    usage: /checkplayer [player]
  adddevotion:
    usage: /adddevotion [player] [aspect] [amount]
  removedevotion:
    usage: /removedevotion [player] [aspect] [amount]
  giveaspect:
    usage: /givedeity [player] [aspect] [major|minor]
  removeaspect:
    usage: /removedeity [player] [aspect]
  setfamily:
    usage: /setfamily [player] [family]
permisions:
  demigods.admin:
    default: op
