name: DemigodsClassic
main: com.demigodsrpg.demigods.classic.DGClassic
version: ${project.version}
description: Ally yourself with mythical deities and battle in the name of the Gods or Titans.
authors: [marinating, HmmmQuestionMark, _Alex, janie177]
softdepend: [WorldGuard, WorldEdit, Multiverse-Core]
commands:
  check:
    usage: /check