name: DemigodsClassic
main: com.demigodsrpg.demigods.classic.DGClassic
version: ${project.version}
description: Ally yourself with mythical deities and battle in the name of the Gods or Titans.
authors: [marinating, HmmmQuestionMark, _Alex, TheFatDemon, janie177]
softdepend: [WorldGuard, WorldEdit, Multiverse-Core]
commands:
  ## Everyday Commands
  alliance:
    usage: /alliance message
    aliases: [a]
  binds:
    usage: /binds
    aliases: [b]
  check:
    usage: /check
    aliases: [c]
  demigods:
    usage: /demigods [subject]
    aliases: [d, dg, demigod]
  shrine:
    usage: /shrine
    aliases: [s, sh, shrines]
  values:
    usage: /values
    aliases: [v]
  ## Admin Commands
  checkplayer:
    usage: /checkplayer [player]
    permissions: demigods.admin.check
  adddevotion:
    usage: /adddevotion [player] [deity] [amount]
    permission: demigods.admin.devotion
  removedevotion:
    usage: /removedevotion [player] [deity] [amount]
    permission: demigods.admin.devotion
  givedeity:
    usage: /givedeity [player] [deity] [major|minor]
    permission: demigods.admin.deity
  removedeity:
    usage: /removedeity [player] [deity]
    permission: demigods.admin.deity
  setalliance:
    usage: /setalliance [player] [alliance]
    permission: demigods.admin.alliance
permisions:
  demigods.admin.check:
    default: op
  demigods.admin.devotion:
    default: op
  demigods.admin.deity:
    default: op
  demigods.admin.alliance:
    default: op