name: DemigodsClassic
main: com.demigodsrpg.demigods.classic.DGClassic
version: ${project.version}
description: Ally yourself with mythical deities and battle in the name of the Gods or Titans.
authors: [marinating, HmmmQuestionMark, _Alex, TheFatDemon, janie177]
softdepend: [WorldGuard, WorldEdit, Multiverse-Core]
commands:
  ## Everyday Commands
  alliance:
    usage: /alliance message
    aliases: [a]
  binds:
    usage: /binds
    aliases: [b]
  check:
    usage: /check
    aliases: [c]
  demigods:
    usage: /demigods [subject]
    aliases: [d, dg, demigod]
  values:
    usage: /values
    aliases: [v]
  ## Admin Commands
  checkplayer:
    usage: /CheckPlayer [Name]
  adddevotion:
    permission: demigods.admin.adddevotion
  removedevotion:
    permission: demigods.admin.removedevotion
  givedeity:
    usage: /GiveDeity [Name, Deity, Major/Minor]
    permission: demigods.admin.givedeity
  removedeity:
    usage: /RemoveDeity [Name, Deity]
    permission: demigods.admin.removedeity
permisions:
  demigods.admin.debug:
    default: op
